### ISSUE TITLE
remove exceptions from linkinator.config.json

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-document-ai#12]

**Comment by bcoe** [comment]
we are waiting on the product documentation to actually be published.

**Comment by bcoe** [comment]
@telpirion likewise, I think we can't remove the exceptions from linkinator configuration until the upstream docs are published?

**Comment by telpirion** [comment]
It looks like this has been addressed already:
https://github.com/googleapis/nodejs-document-ai/blob/master/linkinator.config.json

The linkinator file seems consistent with other Node.js libraries.
I'm going to close this for now. Please feel free to reopen if needed.
