### ISSUE TITLE
Europe endpoint is not supported

### ISSUE THREAD

**Issue by simonebracaloni** [googleapis/nodejs-document-ai#141]
#### Environment details

  - OS: MacOS
  - Node.js version: 10
  - npm version:
  - `@google-cloud/documentai` version: 2.2.2

#### Steps to reproduce

  1. Prepare the sample code
  2. Make any request with location='eu'

The library does not support eu endpoint. Looks like the us endpoint is hardcoded here 
https://github.com/googleapis/nodejs-document-ai/blob/master/src/v1beta3/document_processor_service_client.ts
on _servicePath_ and _apiEndpoint_ stati methods. 

If one try to set 

```
const location = 'eu';
request.name = "projects/${projectId}/locations/${location}/processors/${processorId}"
```

Any call to the api fails with the error:

**3 INVALID_ARGUMENT: Request contains an invalid argument**

**Comment by simonebracaloni** [comment]
Sorry, I found the solution here:
https://github.com/googleapis/nodejs-document-ai/issues/134

**Comment by julianYaman** [comment]
Despite being easily fixed, I just wasted my time because on no official documentation page it was mentioned, that it will use the *US* endpoint by default. This should be added somewhere so new people using the AI will have fewer problems.
