### ISSUE TITLE
Document AI Node.js Client API Reference documentation on version 2.1.1 as "latest version"

### ISSUE THREAD

**Issue by mmdehart** [googleapis/nodejs-document-ai#147]
#### Environment details

  - OS: N/A
  - Node.js version: N/A
  - npm version: N/A
  - `@google-cloud/documentai` version: 2.2.1

#### Steps to reproduce

  1. Visit [https://googleapis.dev/nodejs/documentai/latest/index.html](https://googleapis.dev/nodejs/documentai/latest/index.html)

The info box in bottom right corner has Version: `2.1.1 (latest)`
but latest version is 2.3.0 atm. (as seen in the npm badge at top of page)
![image](https://user-images.githubusercontent.com/5824131/106001582-bf308400-6075-11eb-87a3-cef32f07e087.png)

**Comment by sofisl** [comment]
Thanks for reporting, @mmdehart.

@bcoe, I've retriggered the build of the docs, but I don't see any changes?

**Comment by mmdehart** [comment]
I'm not seeing any changes... what am i missing??

**Comment by bcoe** [comment]
we have fixed the issue and the docs are now up to date with the latest client release (`2.3.0`) 👍 

https://googleapis.dev/nodejs/documentai/2.3.0/index.html
