### ISSUE TITLE
Add support for content being a Buffer

### ISSUE THREAD

**Issue by kolban-google** [googleapis/nodejs-document-ai#151]
As I understand the story today, I can supply a base64 encoded string for the `content` property of a Document object that I wish to process where the content will be either from a PDF, a TIFF or a GIF.  This request asks for consideration of other equivalent data structures such as a NodeJS Buffer.  I am reading GCS data and getting Buffer objects and would like to pass in Buffers without explicitly converting to base64 (in user code) first.

**Comment by munkhuushmgl** [comment]
@kolban-google For feature request, I would recommend you to open new issue here:
 https://issuetracker.google.com

With this note, I am closing the issue.
