### ISSUE TITLE
Bug - error on GCS uri from external project

### ISSUE THREAD

**Issue by MiguiTE** [googleapis/nodejs-document-ai#229]
#### Description

I've got two projects, one with Document AI API enabled and another one to store PDFs on Cloud Storage. I use document ai with a service account which has access to the external Cloud Storage Bucket (where the PDFs are stored). When I call document ai api sending the GCS uri of the pdf it returns "PERMISSION_DENIED". However, the service account has access to the bucket (with uniform permissions configured on the bucket).

I know that the service account has permission to the bucket and the PDFs.

#### Workaround

I can download the PDFs via GCS node client (that's why I know that the service account has access to the object). I download it as base64 and send to te api request

#### Desired behavior

I expected that sending the GCS object uri in the Document AI request would work.
Downloading as base64 is more memory consuming.

#### Environment details

  - OS: Windows 10
  - Node.js version: 14.15.1
  - npm version: 6.14.18
  - `@google-cloud/documentai` version: 2.10.0

#### Steps to reproduce

  1. Create an object in a bucket of Google Cloud Storage from an **external project** (for example with uniform permissions)
  2. Create a service account on the Document AI project
  3. Add that service account to the external project bucket
  4. Make a document ai request to extract parameters from that external bucket

#### Additional info

- The Cloud Storage and Document AI node clients are initialized with the service account.
- The service account is created in the project which has Document AI enabled.

**Comment by munkhuushmgl** [comment]
@MiguiTE 
P4SA on one project cannot access GCS bucket which belongs to other project.

However, SA with sufficient right permissions  can call different project's DocAI processor.

With this note, I am closing this issue.
