### ISSUE TITLE
Files stored in Cloud Storage buckets

### ISSUE THREAD

**Issue by outbackStack** [googleapis/nodejs-document-ai#272]
With Document AI request options, can have something similar to Vision API where we can just enter the Google Bucket URI like below for the file?

```js
const gcsSourceUri = `gs://${bucketName}/${fileName}`;
const name = `projects/${projectId}/locations/${location}/processors/${processorId}`;

const request = {
  name,
  gcsSource: {
    uri: gcsSourceUri,
  },
};

// Recognizes text entities in the PDF document
      const [result] = await client.processDocument(request);
```

[Vision API](https://cloud.google.com/vision/docs/pdf)

**Comment by galz10** [comment]
Hi @outbackStack we have a v1beta2 sample that uses gcs uri, it is for a form but you can delete the ```formExtractionParams``` 

Here's the sample:  https://github.com/googleapis/nodejs-document-ai/blob/main/samples/parse-form.v1beta2.js

**Comment by outbackStack** [comment]
Hi Gal,

Thanks for this. While this gives me the ability to use the gsc uri, it does not allow me to add in the processor id. 

I have had another look at the examples and this one will solve my problem.
https://github.com/googleapis/nodejs-document-ai/blob/main/samples/batch-process-document.js
